stages:
  - test

variables:
  SERVER_CERT: server.crt
  SERVER_KEY: server.key
  CA_CERT: ca.crt
  CLIENT_CERT: client.crt
  CLIENT_KEY: client.key

test_log_injection:
  stage: test
  image: golang:1.24
  before_script:
    - echo "$SERVER_CERT_CONTENT" > $SERVER_CERT || true
    - echo "$SERVER_KEY_CONTENT" > $SERVER_KEY || true
    - echo "$CA_CERT_CONTENT" > $CA_CERT || true
    - echo "$CLIENT_CERT_CONTENT" > $CLIENT_CERT || true
    - echo "$CLIENT_KEY_CONTENT" > $CLIENT_KEY || true

  script:
    - go build -o knox-server ./cmd/dev_server
    - ./knox-server --http :9000 > knox.log 2>&1 &
    - sleep 3
    - curl "http://localhost:9000/v1/keys/%0Ainjected:true%0A"
    - if grep -q "injected:true" knox.log; then echo "Log injection succeeded"; else echo "Log injection failed" && exit 1; fi

  after_script:
    - pkill knox-server || true
