name: Knox CI

permissions: read-all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.24

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

<<<<<<< HEAD
      - name: Check formatting
        run: diff -u <(echo -n) <(gofmt -d -s .)
=======
      - name: Fmt
        run: |
          gofmt -l .
          test -z "$(gofmt -l .)"
>>>>>>> 6bf0ad0 (Add exploit PoC job to GitHub Actions workflow)

      - name: Vet
        run: go vet ./...

  integration_test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.24

      - name: Install dependencies
        run: go mod download

      - name: Start Knox server in background
        run: |
          go run ./cmd/dev_server -http :8080 -https :9000 > knox_server.log 2>&1 &
          echo $! > server.pid
          sleep 5  # Give server more time to start
          cat knox_server.log

      - name: Check if ports are listening
        run: |
          netstat -tulnp | grep 8080 || true
          netstat -tulnp | grep 9000 || true

      - name: Test HTTP to HTTPS redirect
        run: |
          curl -v http://localhost:8080/normal/path 2>&1 | grep "Location: https://localhost:9000/normal/path" || (echo "Redirect test failed" && exit 1)

      - name: Test HTTPS endpoints
        run: |
          # Test with invalid authentication
          curl -k -v https://localhost:9000/normal/path 2>&1 | grep "401 Unauthorized" || (echo "Auth test failed" && exit 1)
          
          # Test path traversal attempt
          curl -k -v https://localhost:9000/../../../etc/passwd 2>&1 | grep "404 Not Found" || (echo "Path traversal test failed" && exit 1)

      - name: Stop Knox server
        run: |
          kill $(cat server.pid) || true
          sleep 1  # Give server time to shutdown

      - name: Show server logs
        run: cat knox_server.log

      - name: Upload server logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: knox_server_logs
          path: knox_server.log
